-- MySQL Script generated by MySQL Workbench
-- Sat Apr 26 14:43:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema acai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema acai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acai` ;
USE `acai` ;

-- -----------------------------------------------------
-- Table `acai`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  `tipo` VARCHAR(1) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_cliente` (
  `idcliente` INT NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(80) NOT NULL,
  `pontos` INT NULL,
  `tb_usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_tb_cliente_tb_usuario1_idx` (`tb_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cliente_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idusuario`)
    REFERENCES `acai`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_produto` (
  `idproduto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(45) NULL,
  `complemento_g` VARCHAR(45) NULL,
  `complemento_p` VARCHAR(45) NULL,
  `cobertura` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_atendente` (
  `idatentende` INT NOT NULL,
  `idade` VARCHAR(3) NOT NULL,
  `horario_chegada` VARCHAR(5) NOT NULL,
  `horario_saida` VARCHAR(5) NOT NULL,
  `descricao` VARCHAR(400) NOT NULL,
  `tb_usuario_idusuario` DATETIME NOT NULL,
  PRIMARY KEY (`idatentende`),
  UNIQUE INDEX `idatentende_UNIQUE` (`idatentende` ASC) VISIBLE,
  INDEX `fk_tb_atentende_tb_usuario1_idx` (`tb_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_atentende_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idusuario`)
    REFERENCES `acai`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_endereco` (
  `idendereco` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `tb_cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_tb_endereco_tb_cliente1_idx` (`tb_cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_endereco_tb_cliente1`
    FOREIGN KEY (`tb_cliente_idcliente`)
    REFERENCES `acai`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `observacao` VARCHAR(200) NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_final` TIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  ` valor_p` DECIMAL(10,2) NOT NULL,
  `taxa_entrega` INT NOT NULL,
  `data` TIMESTAMP NULL,
  `nota_atendente` DECIMAL(2,1) NULL,
  `tb_endereco_idendereco` INT NOT NULL,
  `tb_atentende_idatentende` INT NOT NULL,
  `tb_cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idpedido` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_cliente_idx` (`tb_cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_atentende1_idx` (`tb_atentende_idatentende` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_endereco1_idx` (`tb_endereco_idendereco` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedido_tb_cliente`
    FOREIGN KEY (`tb_cliente_idcliente`)
    REFERENCES `acai`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_atentende1`
    FOREIGN KEY (`tb_atentende_idatentende`)
    REFERENCES `acai`.`tb_atendente` (`idatentende`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_endereco1`
    FOREIGN KEY (`tb_endereco_idendereco`)
    REFERENCES `acai`.`tb_endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `forma_p` DECIMAL(15) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `valor_total` DECIMAL(15) NOT NULL,
  `tb_pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  UNIQUE INDEX `idpagamento_UNIQUE` (`idpagamento` ASC) VISIBLE,
  INDEX `fk_tb_pagamento_tb_pedido1_idx` (`tb_pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pagamento_tb_pedido1`
    FOREIGN KEY (`tb_pedido_idpedido`)
    REFERENCES `acai`.`tb_pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_entrega` (
  `identrega` INT NOT NULL,
  `data_entrega` DATE NOT NULL,
  `horario_entraga` TIME NOT NULL,
  `localizacao` VARCHAR(200) NOT NULL,
  `nota_entrega` DECIMAL(2,1) NULL,
  `tb_pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  INDEX `fk_tb_entrega_tb_pedido1_idx` (`tb_pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_tb_entrega_tb_pedido1`
    FOREIGN KEY (`tb_pedido_idpedido`)
    REFERENCES `acai`.`tb_pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acai`.`tb_itens_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acai`.`tb_itens_pedido` (
  `tb_produto_idproduto` INT NOT NULL,
  `tb_pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`tb_produto_idproduto`, `tb_pedido_idpedido`),
  INDEX `fk_tb_produto_has_tb_pedido_tb_pedido1_idx` (`tb_pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_tb_produto_has_tb_pedido_tb_produto1_idx` (`tb_produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_has_tb_pedido_tb_produto1`
    FOREIGN KEY (`tb_produto_idproduto`)
    REFERENCES `acai`.`tb_produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_has_tb_pedido_tb_pedido1`
    FOREIGN KEY (`tb_pedido_idpedido`)
    REFERENCES `acai`.`tb_pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
